export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SAVEDJOBS = "SAVEDJOBS";
export const SAVEDJOBS_SUCCESS = "SAVEDJOBS_SUCCESS";
export const SAVEDJOBS_FAILED = "SAVEDJOBS_FAILED";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const SAVEDCOMPANY = "SAVEDCOMPANY";
export const SAVEDCOMPANY_SUCCESS = "SAVEDCOMPANY_SUCCESS";
export const SAVEDCOMPANY_FAILED = "SAVEDCOMPANY_FAILED";

