export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SAVEDJOBS = "SAVEDJOBS";
export const SAVEDJOBS_SUCCESS = "SAVEDJOBS_SUCCESS";
export const SAVEDJOBS_FAILED = "SAVEDJOBS_FAILED";

