export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SAVEDJOBS = "SAVEDJOBS";
export const SAVEDJOBS_SUCCESS = "SAVEDJOBS_SUCCESS";
export const SAVEDJOBS_FAILED = "SAVEDJOBS_FAILED";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const SAVEDCOMPANY = "SAVEDCOMPANY";
export const SAVEDCOMPANY_SUCCESS = "SAVEDCOMPANY_SUCCESS";
export const SAVEDCOMPANY_FAILED = "SAVEDCOMPANY_FAILED";

export const GETCANDIDATEID = "GETCANDIDATEID";
export const GETCANDIDATEID_SUCCESS = "GETCANDIDATEID_SUCCESS";
export const GETCANDIDATEID_FAILED = "GETCANDIDATEID_FAILED";

export const SAVEDUSERINTRO = "SAVEDUSERINTRO";
export const SAVEDUSERINTRO_SUCCESS = "SAVEDUSERINTRO_SUCCESS";
export const SAVEDUSERINTRO_FAILED = "SAVEDUSERINTRO_FAILED";

export const SENDRATING = "SENDRATING";
export const SENDRATING_SUCCESS = "SENDRATING_SUCCESS";
export const SENDRATING_FAILED = "SENDRATING_FAILED";

