# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JobSolutions' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobSolutions

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'

end