# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JobSolutions' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobSolutions

  pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  target 'JobSolutionsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'JobSolutions-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobSolutions-tvOS

  target 'JobSolutions-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
